post:
  summary: Create API Key
  operationId: clientApiSettingsV1Post
  responses:
    '200':
      description: Successful creation of API key
      content:
        application/json:
          schema:
            $ref: '../schemas/ApiSettingsResponse.yaml'
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '../schemas/ErrorResponse.yaml'
  tags:
    - API Settings
  security:
    - BearerAuth: []
