openapi: 3.0.3
info:
  title: Safepay API
  version: 1.0.0
servers:
  - url: https://dev.api.getsafepay.com
paths:
  /auth/v1/company/authenticate:
    $ref: './paths/createJWT.yaml'
  /user/v1/guest/:
    $ref: './paths/createGuest.yaml'
  /client/api-settings/v1/:
    $ref: './paths/createAPIKey.yaml'
  /client/passport/v1/token:
    $ref: './paths/generateTimeBasedToken.yaml'
components:
  schemas:
    CreateJWTRequest:
      $ref: './schemas/CreateJWTRequest.yaml'
    CreateJWTResponse:
      $ref: './schemas/CreateJWTResponse.yaml'
    CreateGuestRequest:
      $ref: './schemas/CreateGuestRequest.yaml'
    CreateGuestResponse:
      $ref: './schemas/CreateGuestResponse.yaml'
    CreateAPIKeyResponse:
      $ref: './schemas/CreateAPIKeyResponse.yaml'
    GenerateTimeBasedTokenResponse:
      $ref: './schemas/GenerateTimeBasedTokenResponse.yaml'
    ErrorResponse:
      $ref: './schemas/ErrorResponse.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    merchantSecret:
      type: apiKey
      in: header
      name: X-SFPY-MERCHANT-SECRET
security:
  - bearerAuth: []
  - merchantSecret: []